[package]
name = "oxidots"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
notify = { version = "8.1.0", features = ["serde"] }
log = "0.4"
simplelog = "0.12"  
chrono = "0.4"
